apiVersion: 1

deleteDatasources:
  - name: Prometheus
  - name: Loki

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://tasks.swarmprom_prometheus:9090
  isDefault: true
  version: 1
  editable: true

- name: Loki
  type: loki
  access: proxy
  url: http://tasks.swarmprom_loki:3100
  version: 1
  editable: true
